name: CI Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-main-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-main-m2

    - name: Run CI @ Backend
      run: mvn clean verify
      env:
        MAVEN_OPTS: -Xmx2048m
